version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: api
    volumes:
      - "./data:/app/data"
      - "./env:/app/env"
    env_file:
      - env
    restart: always
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nginx
    ports: 
        - 80:80
    links:
      - api
    depends_on:
      - api
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    restart: always