FROM python:3.7

COPY ./backend/requirements.txt /requirements.txt
RUN pip install -r requirements.txt
COPY ./backend /app
WORKDIR /app

ENTRYPOINT [ "gunicorn" ]
CMD ["-c", "gunicorn.conf.py", "neat.wsgi:application" ]
