# Generated by Django 3.1 on 2020-08-30 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_param', models.BinaryField(help_text='原始参数', max_length=5120)),
                ('position', models.CharField(choices=[('query', 'QUERY'), ('body', 'BODY')], default='unknown', editable=False, help_text='参数位置', max_length=255)),
                ('param_type', models.CharField(choices=[('json', 'JSON'), ('unknown', 'UNKNOWN')], default='unknown', editable=False, help_text='参数类型', max_length=255)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_parmas', to='raw.url')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, help_text='键', max_length=255)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('object', 'Object'), ('unknown', 'Unknown')], default='unknown', editable=False, help_text='值类型', max_length=255)),
                ('values', models.JSONField()),
                ('parnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='normal.param')),
                ('raw_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='normal.rawparam')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='raw.url')),
            ],
            options={
                'ordering': ['url', 'raw_param'],
            },
        ),
        migrations.AddIndex(
            model_name='param',
            index=models.Index(fields=['url', '-raw_param'], name='websiteresult_ordering'),
        ),
    ]
